CREATE TABLE IF NOT EXISTS user_conversations (
    id SERIAL PRIMARY KEY,
    userId BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chatReference VARCHAR(36) NOT NULL,
    chatType VARCHAR(10) NOT NULL DEFAULT 'private',
    otherUserId BIGINT,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(userId, chatReference)
);
