CREATE TABLE IF NOT EXISTS chats (
    id SERIAL PRIMARY KEY,
    chatReference TEXT UNIQUE NOT NUll,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);