CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
    username REFERENCES users(username),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);