CREATE TABLE IF NOT EXISTS chats(
    id SERIAL PRIMARY KEY,
    chatReference UUID UNIQUE NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);