CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);