ALTER TABLE chats
    ADD COLUMN IF NOT EXISTS is_group   BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS name       VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(50);
